### ISSUE TITLE
Is this project alive

### ISSUE THREAD

**Issue by radek-sprta** [theAkito/sue#1]
Hey,
seeing as the last commit is almost a year ago, are you planning to maintain sue?

**Comment by theAkito** [comment]
Sure. It's alive. I just don't use it very often, so I don't have a lot to test. If people test this and tell me what the problem is, I will commit fixes or improvements, if applicable.

If you have further questions, then you are free to ask them. 😃 

Otherwise, you may close the issue, if the information provided was sufficient.

**Comment by radek-sprta** [comment]
Thank you, that's all I needed to know. I was unsure, if I could get any help, should I run into some problem using sue. :)
